spring:
  r2dbc:
    username: accounts-svc
    password: password
    url: r2dbc:h2:mem:///accounts

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.bank.lukgaw.com/auth/realms/bank

server:
  port: 8081

services:
  tx-service:
    host: http://localhost:8082
