spring:
  webflux:
    base-path: /api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://bank.lukgaw.com/auth/realms/bank/protocol/openid-connect/certs

services:
  tx-service:
    host: http://localhost:8082

server:
  port: 8081
