jwt:
  realmAccessRolesMap:
    ACCOUNTS_CUSTOMER: CUSTOMER
    ACCOUNTS_ADMIN: ADMIN

spring:
  webflux:
    base-path: ${BASE_PATH}
  r2dbc:
    username: accounts-svc
    password: password
    url: r2dbc:h2:mem:///accounts

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URL}

services:
  tx-service:
    host: ${TX_SERVICE_URL}
    retry:
      backoff:
        maxAttempts: 3
        backoffSeconds: 1
