spring:
  webflux:
    base-path: /api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.bank.lukgaw.com/auth/realms/bank

services:
  tx-service:
    host: http://localhost:8082

server:
  port: 8081
