version: '3.7'
services:

  gateway:
    image: traefik:v2.6.0
    command:
      - --api.insecure=true
      - --api.dashboard=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
    ports:
      - "80:80" # http
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_DOMAIN}`)
      - traefik.http.routers.keycloak.entrypoints=web
      - traefik.http.routers.keycloak.service=keycloak
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

  keycloak-init:
    image: adorsys/keycloak-config-cli:latest-15.1.1
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=60s
      - IMPORT_PATH=/config
      - IMPORT_FORCE=false
    volumes:
      - ./keycloak-init/config/:/config

  accounts-db:
    image: postgres:13
    hostname: ${ACCOUNTS_DB_HOSTNAME}
    environment:
      POSTGRES_USER: ${ACCOUNTS_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ACCOUNTS_DB_POSTGRES_DB}
    volumes:
      - accounts-db-volume:/var/lib/postgresql/data

volumes:
  accounts-db-volume:
